services:
  - docker

before_install:
- docker pull woodenfish42/build-env-c

script:
- docker run -v `pwd`/src:/tmp -w /tmp woodenfish42/build-env-c:latest sh -c "make all"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - src/tcpfwd
    - src/udpfwd
  skip_cleanup: true
  on:
    tags: true
